In [2]:
import numpy

In [4]:
n=numpy.arange(27)

In [6]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [8]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
import cv2

In [11]:
img=cv2.imread("smallgray.png",1)

In [13]:
print(img)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [14]:
cv2.imwrite("newsmall.png",img)

True

In [25]:
ims=numpy.hstack((img, img, img))

In [26]:
print(ims)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [29]:
lst=numpy.hsplit(ims, 3)

In [30]:
lst

[array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]],
 
        [[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]]], dtype=uint8), array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]],
 
        [[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]]], dtype=uint8), array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 125,